import os
import json
from pathlib import Path
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")

def get_directive() -> str:
    """Reads the experience-director directive."""
    directive_path = Path(__file__).parent.parent / "directives" / "experience-director.md"
    if not directive_path.exists():
        raise FileNotFoundError("Directive experience-director not found.")
    return directive_path.read_text(encoding="utf-8")

def execute_experience_director(enriched_tokens: dict, story_scenes: dict, critic_feedback: str = "", model: str = "anthropic/claude-3-haiku") -> dict:
    """
    Executes the Experience & Spatial Director agent, creating Three.js environments, shaders, and camera positions.
    """
    print(f"[API CALL] Experience & Spatial Director generating WebGL choreography using {model}...")
    
    client = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=OPENROUTER_API_KEY,
    )
    
    system_prompt = get_directive()
    
    user_content = f"Design DNA & Tokens:\n{json.dumps(enriched_tokens, indent=2)}\n\n"
    user_content += f"Story Scenes Storyboard:\n{json.dumps(story_scenes, indent=2)}\n\n"
    if critic_feedback:
        user_content += f"CRITIC FEEDBACK FOR REVISION:\n{critic_feedback}\n\nPlease adjust the WebGL layout to address this critique.\n\n"
    user_content += "Generate the WebGL Spatial Choreography JSON. Remember to output ONLY valid JSON, with NO other text or explanation."
    
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_content}
            ],
            temperature=0.3
        )
        
        raw_output = response.choices[0].message.content.strip()
        
        if raw_output.startswith("```json"):
            raw_output = raw_output[7:]
        if raw_output.startswith("```"):
            raw_output = raw_output[3:]
        if raw_output.endswith("```"):
            raw_output = raw_output[:-3]
            
        webgl_state = json.loads(raw_output.strip())
        print("[SUCCESS] WebGL choreography successfully generated by Spatial Composer AI!")
        return webgl_state
    except Exception as e:
        print(f"[ERROR] Experience & Spatial Director failed: {e}. Executing fallback.")
        colors = enriched_tokens.get("colors", {})
        bg_hex = colors.get("background", "#0F0F0F")
        accent_hex = colors.get("accent", "#CCFF00")
        
        return {
            "webgl_theme": "luxury",
            "global_camera_settings": {
                "fov": 45,
                "near": 0.1,
                "far": 1000
            },
            "environment": {
                "fog_density": 0.015,
                "fog_color": bg_hex,
                "lights": [
                    {
                        "type": "ambient",
                        "color": "#ffffff",
                        "intensity": 0.5,
                        "position": [0, 0, 0]
                    },
                    {
                        "type": "spotlight",
                        "color": accent_hex,
                        "intensity": 2.0,
                        "position": [5, 10, 5]
                    }
                ],
                "ambient_particles": {
                    "type": "gold_dust",
                    "count": 500,
                    "color": accent_hex,
                    "speed": 0.3
                }
            },
            "scene_choreography": [
                {
                    "scene_number": 1,
                    "camera_path_step": {
                        "position": [0, 2, 10],
                        "lookAt": [0, 0, 0],
                        "transition_ease": "easeOutExpo",
                        "scroll_trigger_range": [0.0, 0.33]
                    },
                    "three_js_elements": [
                        {
                            "type": "mesh",
                            "query": "hero_abstract_shape",
                            "material": "glass",
                            "shader_custom_effects": {
                                "refraction": True,
                                "chromatic_aberration": 0.04,
                                "liquid_movement": False
                            },
                            "position": [0, 0, 0],
                            "rotation": [0, 0.78, 0],
                            "scale": [1.5, 1.5, 1.5]
                        }
                    ]
                }
            ]
        }

if __name__ == "__main__":
    sample_tokens = {
        "brand": {"name": "Gino Yachting", "archetype": "ruler"},
        "colors": {"background": "#02050A", "accent": "#b49554"}
    }
    sample_story = {
        "scenes": [
            {"scene_number": 1, "name": "The Sea", "metaphor": "Sea wireframe mesh"}
        ]
    }
    print(json.dumps(execute_experience_director(sample_tokens, sample_story), indent=2, ensure_ascii=False))
