# -*- coding: utf-8 -*-
"""
ANDIP 3D Scene Generator
Generates a structured scene_state.json for autonomous WebGL 3D / scroll-driven experiences.
"""

import os
import json
from pathlib import Path
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")

def execute_scene_generator(enriched_tokens: dict, visual_language: dict, experience_flow: dict, motion_graph: dict, model: str = "anthropic/claude-3-haiku") -> dict:
    """
    Executes the 3D Scene Generator, producing a structured scene_state.json.
    Includes custom fallback mechanisms for reliability.
    """
    print(f"[API CALL] Scene Generator generating 3D scene state JSON using {model}...")
    
    # 1. Fetch 3D and spatial properties from DNA
    spatial_depth = enriched_tokens.get("spatial_depth", "mid")
    camera_movement = enriched_tokens.get("camera_movement_style", "dive")
    shader_type = enriched_tokens.get("shader_type", "glass")
    models_3d = enriched_tokens.get("required_3d_models", [])
    
    # Core aesthetic parameters
    core_emotion = enriched_tokens.get("emotion", {}).get("id", "trustworthy")
    brand_name = enriched_tokens.get("brand", {}).get("name", "Exclusive Brand")
    colors = enriched_tokens.get("colors", {})
    
    # 2. Try calling LLM to orchestrate the 3D scene creatively
    system_prompt = f"""You are the Spatial Composer and 3D Director AI Agent for ANDIP (AI Native Design Intelligence Platform).
Your job is to translate a brand's Design DNA, visual system, and text content into a cinematic, scroll-driven 3D WebGL Scene Choreography.

You must output ONLY a valid JSON object matching the schema below. DO NOT include any markdown blocks (like ```json), explanations, or notes. Just the raw JSON.

### SCENE STATE JSON SCHEMA:
{{
  "theme": "string (luxury | cyberpunk | brutalist | minimalist | organic)",
  "camera": {{
    "path": "string (pan | orbit | dive | zoom | static)",
    "speed": 1.2,
    "fov": 45
  }},
  "environment": {{
    "type": "string (dark | light | neon | night | studio)",
    "particles": "string (gold_dust | stars | embers | rain | none)",
    "bg_color": "string (hex color)"
  }},
  "scenes": [
    {{
      "scrollTrigger": 0.0,
      "type": "kinetic_typography",
      "text": "Header Title",
      "subtitle": "Sub-header or tag",
      "position": [0.0, 1.0, 0.0],
      "color": "#ffffff"
    }},
    {{
      "scrollTrigger": 0.3,
      "type": "3d_model",
      "query": "string (e.g. luxury_yacht, sports_car, sneaker, katana)",
      "material": "string (glass | gold | chrome | neon | matte | default)",
      "position": [2.0, 0.0, -10.0],
      "rotation": [0.0, 1.57, 0.0],
      "scale": [1.0, 1.0, 1.0],
      "description": "Copywriting text mapped from layout"
    }}
  ]
}}

### CREATIVE DIRECTIVES:
- Match the environment and particles perfectly to the core emotion:
  * luxury -> Night / studio environment with 'gold_dust' particles.
  * calm / organic -> Light environment with 'stars' or 'none'.
  * cyberpunk / aggressive -> Neon / night environment with 'embers' or 'rain'.
- Align camera path:
  * If models have horizontal profiles (like cars/yachts), prefer 'pan' or 'orbit'.
  * If models are high-tactile (like sneakers or cosmetic bottles), prefer 'dive' or 'zoom'.
  * If the theme is editorial/manifesto, prefer 'dive' or 'static' focusing on kinetic typography.
- Dynamically parse the UX layout sections and place them as scroll-driven scene keys between 0.0 and 1.0 scroll triggers.
"""

    user_content = f"""Design DNA:
{json.dumps(enriched_tokens, indent=2)}

Visual Language:
{json.dumps(visual_language, indent=2)}

UX Layout Sections:
{json.dumps(experience_flow, indent=2)}

Motion Configuration:
{json.dumps(motion_graph, indent=2)}

Generate the 3D Scene State JSON. Output ONLY valid JSON."""

    try:
        client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=OPENROUTER_API_KEY,
        )
        
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_content}
            ],
            temperature=0.3
        )
        
        raw_output = response.choices[0].message.content.strip()
        
        # Clean markdown wraps
        if raw_output.startswith("```json"):
            raw_output = raw_output[7:]
        if raw_output.startswith("```"):
            raw_output = raw_output[3:]
        if raw_output.endswith("```"):
            raw_output = raw_output[:-3]
            
        scene_state = json.loads(raw_output.strip())
        print("[SUCCESS] Dynamic 3D Scene state JSON successfully generated by AI!")
        return scene_state
        
    except Exception as e:
        print(f"[SCENE GENERATOR WARNING] Failed to generate scene state via LLM: {e}. Executing robust local fallback.")
        
        # Determine background and primary color
        bg_hex = colors.get("background", "#02050A")
        accent_hex = colors.get("accent", "#b49554")
        
        # Map particle type
        particles_map = "none"
        if core_emotion == "luxury":
            particles_map = "gold_dust"
        elif core_emotion in ["cyberpunk", "aggressive"]:
            particles_map = "embers"
        elif core_emotion == "calm":
            particles_map = "stars"
            
        # Determine default model query
        fallback_model = "abstract_shape"
        if models_3d:
            fallback_model = models_3d[0]
        elif "yacht" in brand_name.lower() or "marine" in brand_name.lower():
            fallback_model = "luxury_yacht"
        elif "car" in brand_name.lower() or "auto" in brand_name.lower():
            fallback_model = "sports_car"
            
        # Determine shader material
        material_map = "default"
        if shader_type == "glass":
            material_map = "glass"
        elif shader_type == "water-gold" or core_emotion == "luxury":
            material_map = "gold"
        elif shader_type == "neon-glitch":
            material_map = "neon"
            
        # Create fallbacks based on sections
        sections = experience_flow.get("sections", [])
        scenes_fallback = []
        
        num_sections = len(sections) if sections else 3
        for idx, sec in enumerate(sections):
            trigger_progress = round(idx / max(1, num_sections - 1), 2)
            sec_title = sec.get("title", f"Section {idx + 1}")
            sec_desc = sec.get("description", "")
            
            # Alternate between kinetic text and 3D model reveals
            if idx % 2 == 0 or idx == 0:
                scenes_fallback.append({
                    "scrollTrigger": trigger_progress,
                    "type": "kinetic_typography",
                    "text": sec_title.upper(),
                    "subtitle": sec_desc,
                    "position": [0.0, 1.0, -5.0 * idx],
                    "color": "#ffffff"
                })
            else:
                scenes_fallback.append({
                    "scrollTrigger": trigger_progress,
                    "type": "3d_model",
                    "query": fallback_model,
                    "material": material_map,
                    "position": [2.0 if idx % 4 == 1 else -2.0, 0.0, -10.0 - (5.0 * idx)],
                    "rotation": [0.0, 0.78, 0.0],
                    "scale": [1.0, 1.0, 1.0],
                    "description": sec_desc
                })
                
        fallback_state = {
            "theme": core_emotion,
            "camera": {
                "path": camera_movement,
                "speed": 1.2,
                "fov": 50
            },
            "environment": {
                "type": "night" if core_emotion != "calm" else "light",
                "particles": particles_map,
                "bg_color": bg_hex
            },
            "scenes": scenes_fallback
        }
        
        print("[SUCCESS] Local 3D Scene state fallback JSON successfully generated.")
        return fallback_state

if __name__ == "__main__":
    # Test generation
    sample_tokens = {
        "spatial_depth": "far",
        "camera_movement_style": "orbit",
        "shader_type": "water-gold",
        "required_3d_models": ["luxury_yacht"],
        "emotion": {"id": "luxury"},
        "brand": {"name": "Gino Yachting"},
        "colors": {"background": "#02050A", "accent": "#b49554"}
    }
    sample_visual = {"color_tokens": {"background": "#02050A", "accent": "#b49554"}}
    sample_flow = {"sections": [{"title": "Gino Group", "description": "Serving excellence"}, {"title": "History", "description": "Our heritage"}]}
    sample_motion = {}
    print(json.dumps(execute_scene_generator(sample_tokens, sample_visual, sample_flow, sample_motion), indent=2, ensure_ascii=False))
