import os
import json
from pathlib import Path
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")

def get_directive() -> str:
    """Reads the story-architect directive."""
    directive_path = Path(__file__).parent.parent / "directives" / "story-architect.md"
    if not directive_path.exists():
        raise FileNotFoundError("Directive story-architect not found.")
    return directive_path.read_text(encoding="utf-8")

def execute_story_architect(enriched_tokens: dict, critic_feedback: str = "", model: str = "anthropic/claude-3.5-sonnet") -> dict:
    """
    Executes the Story Architect agent, breaking down the brand voice/DNA into 6-10 narrative scenes.
    """
    # Safety check for model spelling typos
    if "claude-3-5" in model:
        model = "anthropic/claude-3.5-sonnet"
    print(f"[API CALL] Story Architect generating narrative arc using {model}...")
    
    client = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=OPENROUTER_API_KEY,
    )
    
    system_prompt = get_directive()
    
    user_content = f"Design DNA & Tokens:\n{json.dumps(enriched_tokens, indent=2)}\n\n"
    if critic_feedback:
        user_content += f"CRITIC FEEDBACK FOR REVISION:\n{critic_feedback}\n\nPlease adjust the narrative storyboard/scenes to address this critique.\n\n"
    user_content += "Generate the Story Storyboard/Scenes JSON. Remember to output ONLY valid JSON, with NO other text or explanation."
    
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_content}
            ],
            temperature=0.4
        )
        
        raw_output = response.choices[0].message.content.strip()
        
        if raw_output.startswith("```json"):
            raw_output = raw_output[7:]
        if raw_output.startswith("```"):
            raw_output = raw_output[3:]
        if raw_output.endswith("```"):
            raw_output = raw_output[:-3]
            
        story_scenes = json.loads(raw_output.strip())
        print("[SUCCESS] Narrative story state successfully generated by AI!")
        return story_scenes
    except Exception as e:
        print(f"[ERROR] Story Architect failed: {e}. Executing robust fallback.")
        brand_name = enriched_tokens.get("brand", {}).get("name", "Exclusive Experience")
        return {
            "project_narrative_arc": f"A cinematic interactive showcase presenting the visual legacy of {brand_name}.",
            "scenes": [
                {
                  "scene_number": 1,
                  "name": "The Genesis / Giriş",
                  "metaphor": "Slow zoom sweep through absolute stillness.",
                  "vibe": "minimalist",
                  "visual_trigger": "Slight camera motion on scroll revealing primary titles.",
                  "copywriting_header": brand_name.upper(),
                  "copywriting_body": f"Discover the reimagined future of digital craftsmanship.",
                  "narrative_goal": "Establish primary high-end brand authority."
                },
                {
                  "scene_number": 2,
                  "name": "The Craft / Derinleşme",
                  "metaphor": "3D wireframe mesh rising from the darkness.",
                  "vibe": "luxury",
                  "visual_trigger": "Structural particles start floating around a central shape.",
                  "copywriting_header": "UNCOMPROMISING DETAIL",
                  "copywriting_body": "Every single border, shadow, and coordinate mathematically aligned to absolute perfection.",
                  "narrative_goal": "Evoke sense of premium custom attention to details."
                },
                {
                  "scene_number": 3,
                  "name": "Interactive Contact / Eylem",
                  "metaphor": "Camera settling into an immersive grid dashboard interface.",
                  "vibe": "minimalist",
                  "visual_trigger": "Elements scale gently into focus presenting the action paths.",
                  "copywriting_header": "JOIN THE VANGUARD",
                  "copywriting_body": "Ready to design tomorrow? Connect with our intelligence network.",
                  "narrative_goal": "Trigger direct interactive connection."
                }
            ]
        }

if __name__ == "__main__":
    sample_tokens = {
        "brand": {"name": "Test Boutique", "archetype": "ruler"},
        "emotion": {"id": "luxury"}
    }
    print(json.dumps(execute_story_architect(sample_tokens), indent=2, ensure_ascii=False))
